### ISSUE TITLE
Add github actions

### ISSUE THREAD

**Issue by nikola-rados** [pacificclimate/wps-tools#1]
Now that the repo is up we want to get our CI tools in!

**Comment by eyvorchuk** [comment]
Since this repo isn't used by itself, but rather by the birds, does it not need a `requirements.txt` file containing any packages that are imported in the `.py` files? In which case, the only action we need is to set up the proper python version?

**Comment by nikola-rados** [comment]
So we will want a `requirements.txt` since we will be using `pywps` along with other packages.

In terms of actions we would want I think there are two, integration tests and pypi publishing. Even though the birds will be using these functions we still need to test them in this repo. That means putting together a test suite that can be run on pushes.  Plus since this is meant to be a package we want to have it automatically publish once a new tag has been pushed.
